name: user_repository
description: A User Dart Repository
version: 1.0.0+1
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter_secure_storage: ^5.0.2
  dio: ^4.0.6
  firebase_auth: ^3.3.19
  equatable: ^2.0.3
