name: feedback24_app
description: A new Flutter project.

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:  
  flutter:
    sdk: flutter
  equatable: ^2.0.0
  fresh_dio: ^0.3.2
  flutter_bloc: ^8.0.0
  feedback_api_client:
    path: packages/feedback_api_client
  user_repository:
    path: packages/user_repository
  flutter_spinkit: ^5.1.0
  flutter_secure_storage: ^5.0.2
  email_validator: ^2.0.1
  country_code_picker: ^2.0.2
  flutter_svg: ^1.1.0
  meta: ^1.7.0
  go_router: ^3.1.1
  formz: ^0.4.1
  yandex_mapkit: ^3.0.1
  get_it: ^7.2.0
  dialog: ^0.8.0
  flutter_html: ^0.11.1
  location: ^4.4.0
  connectivity: ^3.0.6
  connectivity_plus: ^2.3.6
  internet_connection_checker: ^0.0.1+4
  data_connection_checker: ^0.3.4
  rflutter_alert: ^2.0.4




  image_picker: ^0.8.3


dev_dependencies:
  build_runner:
  flutter_gen_runner:

flutter_gen:
  integrations:
    flutter_svg: true
    rive: true

flutter:
  uses-material-design: true
  
  assets: 
  - assets/images/



  


